# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            CSA_Blog
description:      'CSA_Blog'
url:              https://iwu78.github.io
baseurl:          '/ian_2025'
remote_theme:     fongandrew/hydeout

author:
  name:           'Ian Wu'
  url:            https://github.com/iwu78

paginate:         5

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-include-cache
  - jemoji
  - jekyll-remote-theme

exclude:
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
  - .gitignore

permalink:        /:year/:month/:day/:title.html

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      excerpt_separator:  <!--more-->
      layout: post

# Sidebar link settings
sidebar_home_link:  true

exclude:
  - venv
